
server:
  port: ${APP_PORT:8080}

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/rag_chat}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:Pass@123}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  #ssl:
    #bundle:
      #jks:
        #llmTrust:
          #truststore:
            #location: classpath:llm-truststore.jks
            #password: mysecretpass
            #type: jks

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    root: ${LOG_LEVEL:INFO}

# Example custom props for LLM
llm:
  base-url: https://api.openai.com
  timeout-ms: 30000
